<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $this->command->info('  Create 30 products successfully!');

        $products = [
            // Fruits
            [
                'name' => ['en'=>'Red Apple','ar'=>'تفاح أحمر'],
                'unit' => ['en'=>'kg','ar'=>'كجم'],
                'sku' => 'PRD-APL-001',
                'barcode' => '1000001',
                'price' => 2.99,
                'sale_price' => 3.50,
                'stock' => 50,
                'rate' => 4,
                'description' => ['en'=>'Fresh red apples from local farms.','ar'=>'تفاح أحمر طازج من المزارع المحلية.'],
                'nutrition' => ['en'=>'Vitamin C, Fiber','ar'=>'فيتامين سي، ألياف'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/apple.png',
            ],
            [
                'name' => ['en'=>'Banana','ar'=>'موز'],
                'unit' => ['en'=>'kg','ar'=>'كجم'],
                'sku' => 'PRD-BAN-002',
                'barcode' => '1000002',
                'price' => 1.90,
                'sale_price' => 2.20,
                'stock' => 100,
                'rate' => 5,
                'description' => ['en'=>'Sweet yellow bananas.','ar'=>'موز أصفر حلو.'],
                'nutrition' => ['en'=>'Potassium, Vitamin B6','ar'=>'بوتاسيوم، فيتامين ب6'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/banana.png',
            ],
            [
                'name' => ['en'=>'Orange','ar'=>'برتقال'],
                'unit' => ['en'=>'kg','ar'=>'كجم'],
                'sku' => 'PRD-ORG-003',
                'barcode' => '1000003',
                'price' => 2.50,
                'sale_price' => 2.80,
                'stock' => 80,
                'rate' => 4,
                'description' => ['en'=>'Juicy oranges.','ar'=>'برتقال عصيري.'],
                'nutrition' => ['en'=>'Vitamin C','ar'=>'فيتامين سي'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/orange.png',
            ],
            [
                'name' => ['en'=>'Grapes','ar'=>'عنب'],
                'unit' => ['en'=>'kg','ar'=>'كجم'],
                'sku' => 'PRD-GRP-004',
                'barcode' => '1000004',
                'price' => 3.50,
                'sale_price' => 4.00,
                'stock' => 40,
                'rate' => 5,
                'description' => ['en'=>'Sweet green grapes.','ar'=>'عنب أخضر حلو.'],
                'nutrition' => ['en'=>'Antioxidants','ar'=>'مضادات الأكسدة'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/grapes.png',
            ],
            [
                'name' => ['en'=>'Watermelon','ar'=>'بطيخ'],
                'unit' => ['en'=>'pcs','ar'=>'حبة'],
                'sku' => 'PRD-WML-005',
                'barcode' => '1000005',
                'price' => 5.50,
                'sale_price' => 6.00,
                'stock' => 20,
                'rate' => 4,
                'description' => ['en'=>'Large fresh watermelon.','ar'=>'بطيخ طازج كبير.'],
                'nutrition' => ['en'=>'Hydration, Vitamin A','ar'=>'ترطيب، فيتامين أ'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/watermelon.png',
            ],

            // Dairy
            [
                'name' => ['en'=>'Milk 1L','ar'=>'حليب 1 لتر'],
                'unit' => ['en'=>'L','ar'=>'لتر'],
                'sku' => 'PRD-MIL-011',
                'barcode' => '1000011',
                'price' => 0.99,
                'sale_price' => 1.20,
                'stock' => 80,
                'rate' => 3,
                'description' => ['en'=>'Whole milk bottle.','ar'=>'زجاجة حليب كامل الدسم.'],
                'nutrition' => ['en'=>'Calcium, Protein','ar'=>'كالسيوم، بروتين'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/milk.png',
            ],
            [
                'name' => ['en'=>'Yogurt 500g','ar'=>'زبادي 500 جم'],
                'unit' => ['en'=>'pcs','ar'=>'علبة'],
                'sku' => 'PRD-YOG-012',
                'barcode' => '1000012',
                'price' => 1.20,
                'sale_price' => 1.50,
                'stock' => 60,
                'rate' => 4,
                'description' => ['en'=>'Natural yogurt cup.','ar'=>'علبة زبادي طبيعي.'],
                'nutrition' => ['en'=>'Probiotics','ar'=>'بروبيوتيك'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/yogurt.png',
            ],
            [
                'name' => ['en'=>'Cheddar Cheese 200g','ar'=>'جبنة شيدر 200 جم'],
                'unit' => ['en'=>'pcs','ar'=>'قطعة'],
                'sku' => 'PRD-CHD-013',
                'barcode' => '1000013',
                'price' => 2.40,
                'sale_price' => 2.80,
                'stock' => 40,
                'rate' => 5,
                'description' => ['en'=>'Mature cheddar cheese.','ar'=>'جبنة شيدر ناضجة.'],
                'nutrition' => ['en'=>'Protein, Calcium','ar'=>'بروتين، كالسيوم'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/cheddar.png',
            ],
            [
                'name' => ['en'=>'Butter 250g','ar'=>'زبدة 250 جم'],
                'unit' => ['en'=>'pcs','ar'=>'قطعة'],
                'sku' => 'PRD-BUT-014',
                'barcode' => '1000014',
                'price' => 2.20,
                'sale_price' => 2.50,
                'stock' => 30,
                'rate' => 4,
                'description' => ['en'=>'Creamy butter block.','ar'=>'قطعة زبدة كريمية.'],
                'nutrition' => ['en'=>'Fat, Vitamin A','ar'=>'دهون، فيتامين أ'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/butter.png',
            ],
            [
                'name' => ['en'=>'Eggs 12pcs','ar'=>'بيض 12 حبة'],
                'unit' => ['en'=>'pack','ar'=>'علبة'],
                'sku' => 'PRD-EGG-015',
                'barcode' => '1000015',
                'price' => 2.00,
                'sale_price' => 2.40,
                'stock' => 200,
                'rate' => 5,
                'description' => ['en'=>'Farm fresh eggs.','ar'=>'بيض طازج من المزرعة.'],
                'nutrition' => ['en'=>'Protein','ar'=>'بروتين'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/eggs.png',
            ],

            // Vegetables
            [
                'name' => ['en'=>'Tomato','ar'=>'طماطم'],
                'unit' => ['en'=>'kg','ar'=>'كجم'],
                'sku' => 'PRD-TOM-006',
                'barcode' => '1000006',
                'price' => 1.70,
                'sale_price' => 2.00,
                'stock' => 70,
                'rate' => 3,
                'description' => ['en'=>'Fresh red tomatoes.','ar'=>'طماطم حمراء طازجة.'],
                'nutrition' => ['en'=>'Vitamin C, Lycopene','ar'=>'فيتامين سي، لايكوبين'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/tomato.jpg',
            ],
            [
                'name' => ['en'=>'Cucumber','ar'=>'خيار'],
                'unit' => ['en'=>'kg','ar'=>'كجم'],
                'sku' => 'PRD-CUC-007',
                'barcode' => '1000007',
                'price' => 1.30,
                'sale_price' => 1.60,
                'stock' => 60,
                'rate' => 4,
                'description' => ['en'=>'Crispy cucumbers.','ar'=>'خيار مقرمش.'],
                'nutrition' => ['en'=>'Hydration','ar'=>'ترطيب'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/cucumber.png',
            ],
            [
                'name' => ['en'=>'Potato','ar'=>'بطاطس'],
                'unit' => ['en'=>'kg','ar'=>'كجم'],
                'sku' => 'PRD-POT-008',
                'barcode' => '1000008',
                'price' => 2.00,
                'sale_price' => 2.40,
                'stock' => 90,
                'rate' => 3,
                'description' => ['en'=>'Brown potatoes.','ar'=>'بطاطس بنية.'],
                'nutrition' => ['en'=>'Carbohydrates','ar'=>'كربوهيدرات'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/potato.jpg',
            ],
            [
                'name' => ['en'=>'Onion','ar'=>'بصل'],
                'unit' => ['en'=>'kg','ar'=>'كجم'],
                'sku' => 'PRD-ONI-009',
                'barcode' => '1000009',
                'price' => 1.20,
                'sale_price' => 1.50,
                'stock' => 100,
                'rate' => 4,
                'description' => ['en'=>'Yellow onions.','ar'=>'بصل أصفر.'],
                'nutrition' => ['en'=>'Antioxidants','ar'=>'مضادات الأكسدة'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/onion.jpg',
            ],
            [
                'name' => ['en'=>'Carrot','ar'=>'جزر'],
                'unit' => ['en'=>'kg','ar'=>'كجم'],
                'sku' => 'PRD-CAR-010',
                'barcode' => '1000010',
                'price' => 1.80,
                'sale_price' => 2.20,
                'stock' => 50,
                'rate' => 5,

                'description' => ['en'=>'Crunchy carrots.','ar'=>'جزر مقرمش.'],
                'nutrition' => ['en'=>'Beta-carotene','ar'=>'بيتا كاروتين'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/carrots.jpg',
            ],

            // Beverages
            [
                'name' => ['en'=>'Water 1.5L','ar'=>'ماء 1.5 لتر'],
                'unit' => ['en'=>'L','ar'=>'لتر'],
                'sku' => 'PRD-WTR-016',
                'barcode' => '1000016',
                'price' => 0.50,
                'sale_price' => 0.70,
                'stock' => 150,
                'rate' => 3,
                'description' => ['en'=>'Mineral water bottle.','ar'=>'زجاجة ماء معدني.'],
                'nutrition' => ['en'=>'Hydration','ar'=>'ترطيب'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/water.jpg',
            ],
            [
                'name' => ['en'=>'Orange Juice 1L','ar'=>'عصير برتقال 1 لتر'],
                'unit' => ['en'=>'L','ar'=>'لتر'],
                'sku' => 'PRD-OJ-017',
                'barcode' => '1000017',
                'price' => 2.20,
                'sale_price' => 2.50,
                'stock' => 120,
                'rate' => 4,
                'description' => ['en'=>'Fresh orange juice.','ar'=>'عصير برتقال طازج.'],
                'nutrition' => ['en'=>'Vitamin C','ar'=>'فيتامين سي'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/orange-juice.jpg',
            ],
            [
                'name' => ['en'=>'Cola 330ml','ar'=>'كولا 330 مل'],
                'unit' => ['en'=>'ml','ar'=>'مل'],
                'sku' => 'PRD-COL-018',
                'barcode' => '1000018',
                'price' => 0.99,
                'sale_price' => 1.20,
                'stock' => 200,
                'rate' => 5,
                'description' => ['en'=>'Sparkling cola drink.','ar'=>'مشروب كولا غازي.'],
                'nutrition' => ['en'=>'Sugar, Caffeine','ar'=>'سكر، كافيين'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/cola.png',
            ],
            [
                'name' => ['en'=>'Coffee 200g','ar'=>'قهوة 200 جم'],
                'unit' => ['en'=>'g','ar'=>'جم'],
                'sku' => 'PRD-CFF-019',
                'barcode' => '1000019',
                'price' => 4.50,
                'sale_price' => 5.00,
                'stock' => 60,
                'rate' => 4,
                'description' => ['en'=>'Roasted coffee beans.','ar'=>'حبوب قهوة محمصة.'],
                'nutrition' => ['en'=>'Caffeine, Antioxidants','ar'=>'كافيين، مضادات الأكسدة'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/coffee.jpg',
            ],
            [
                'name' => ['en'=>'Tea Box','ar'=>'علبة شاي'],
                'unit' => ['en'=>'pack','ar'=>'علبة'],
                'sku' => 'PRD-TEA-020',
                'barcode' => '1000020',
                'price' => 2.40,
                'sale_price' => 2.80,
                'stock' => 100,
                'rate' => 3,
                'description' => ['en'=>'Black tea bags.','ar'=>'أكياس شاي أسود.'],
                'nutrition' => ['en'=>'Antioxidants','ar'=>'مضادات الأكسدة'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/tea.jpg',
            ],

            // Bakery & Snacks
            [
                'name' => ['en'=>'Bread Loaf','ar'=>'رغيف خبز'],
                'unit' => ['en'=>'pcs','ar'=>'قطعة'],
                'sku' => 'PRD-BK-021',
                'barcode' => '1000021',
                'price' => 1.20,
                'sale_price' => 1.50,
                'stock' => 80,
                'rate' => 4,
                'description' => ['en'=>'Fresh baked bread loaf.','ar'=>'رغيف خبز طازج.'],
                'nutrition' => ['en'=>'Carbs, Fiber','ar'=>'كربوهيدرات، ألياف'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/bread.jpg',
            ],
            [
                'name' => ['en'=>'Croissant','ar'=>'كرواسون'],
                'unit' => ['en'=>'pcs','ar'=>'قطعة'],
                'sku' => 'PRD-BK-022',
                'barcode' => '1000022',
                'price' => 0.80,
                'sale_price' => 1.00,
                'stock' => 120,
                'rate' => 5,
                'description' => ['en'=>'Butter croissant.','ar'=>'كرواسون بالزبدة.'],
                'nutrition' => ['en'=>'Carbs, Fat','ar'=>'كربوهيدرات، دهون'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/croissant.jpg',
            ],
            [
                'name' => ['en'=>'Chocolate Chip Cookies','ar'=>'بسكويت برقائق الشوكولاتة'],
                'unit' => ['en'=>'pack','ar'=>'علبة'],
                'sku' => 'PRD-BK-023',
                'barcode' => '1000023',
                'price' => 2.10,
                'sale_price' => 2.50,
                'stock' => 90,
                'rate' => 5,
                'description' => ['en'=>'Crispy chocolate chip cookies.','ar'=>'بسكويت مقرمش برقائق الشوكولاتة.'],
                'nutrition' => ['en'=>'Carbs, Sugar','ar'=>'كربوهيدرات، سكر'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/cookies.jpg',
            ],
            [
                'name' => ['en'=>'Muffins','ar'=>'مافن'],
                'unit' => ['en'=>'pack','ar'=>'علبة'],
                'sku' => 'PRD-BK-024',
                'barcode' => '1000024',
                'price' => 2.60,
                'sale_price' => 3.00,
                'stock' => 70,
                'rate' => 4,
                'description' => ['en'=>'Assorted muffins pack.','ar'=>'علبة مافن متنوعة.'],
                'nutrition' => ['en'=>'Carbs, Sugar','ar'=>'كربوهيدرات، سكر'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/muffins.png',
            ],
            [
                'name' => ['en'=>'Baguette','ar'=>'باغيت'],
                'unit' => ['en'=>'pcs','ar'=>'قطعة'],
                'sku' => 'PRD-BK-025',
                'barcode' => '1000025',
                'price' => 1.10,
                'sale_price' => 1.30,
                'stock' => 60,
                'rate' => 4,
                'description' => ['en'=>'Classic French baguette.','ar'=>'باغيت فرنسي كلاسيكي.'],
                'nutrition' => ['en'=>'Carbs','ar'=>'كربوهيدرات'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/baguette.jpg',
            ],
            [
                'name' => ['en'=>'Donuts 6pcs','ar'=>'دونات 6 حبات'],
                'unit' => ['en'=>'pack','ar'=>'علبة'],
                'sku' => 'PRD-BK-026',
                'barcode' => '1000026',
                'price' => 3.20,
                'sale_price' => 3.80,
                'stock' => 50,
                'rate' => 5,
                'description' => ['en'=>'Glazed donuts pack.','ar'=>'علبة دونات مزججة.'],
                'nutrition' => ['en'=>'Carbs, Sugar, Fat','ar'=>'كربوهيدرات، سكر، دهون'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/donuts.jpg',
            ],
            [
                'name' => ['en'=>'Crackers','ar'=>'بسكويت مالح'],
                'unit' => ['en'=>'pack','ar'=>'علبة'],
                'sku' => 'PRD-BK-027',
                'barcode' => '1000027',
                'price' => 1.90,
                'sale_price' => 2.20,
                'stock' => 110,
                'rate' => 3,
                'description' => ['en'=>'Salted crackers.','ar'=>'بسكويت مالح.'],
                'nutrition' => ['en'=>'Carbs, Salt','ar'=>'كربوهيدرات، ملح'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/crackers.jpg',
            ],
            [
                'name' => ['en'=>'Sandwich Bread','ar'=>'خبز ساندويتش'],
                'unit' => ['en'=>'pack','ar'=>'علبة'],
                'sku' => 'PRD-BK-028',
                'barcode' => '1000028',
                'price' => 1.70,
                'sale_price' => 2.10,
                'stock' => 95,
                'rate' => 4,
                'description' => ['en'=>'Soft sandwich bread.','ar'=>'خبز ساندويتش طري.'],
                'nutrition' => ['en'=>'Carbs, Fiber','ar'=>'كربوهيدرات، ألياف'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/sandwich-bread.jpg',
            ],
            [
                'name' => ['en'=>'Pretzels','ar'=>'بريتزل'],
                'unit' => ['en'=>'pack','ar'=>'علبة'],
                'sku' => 'PRD-BK-029',
                'barcode' => '1000029',
                'price' => 1.60,
                'sale_price' => 1.90,
                'stock' => 85,
                'rate' => 3,
                'description' => ['en'=>'Baked pretzel snacks.','ar'=>'وجبة خفيفة بريتزل مخبوزة.'],
                'nutrition' => ['en'=>'Carbs, Salt','ar'=>'كربوهيدرات، ملح'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/pretzels.jpg',
            ],
            [
                'name' => ['en'=>'Granola Bars','ar'=>'ألواح جرنولا'],
                'unit' => ['en'=>'pack','ar'=>'علبة'],
                'sku' => 'PRD-BK-030',
                'barcode' => '1000030',
                'price' => 2.80,
                'sale_price' => 3.20,
                'stock' => 75,
                'rate' => 5,
                'description' => ['en'=>'Mixed granola bars.','ar'=>'ألواح جرنولا.'],
                'nutrition' => ['en'=>'Fiber, Nuts','ar'=>'ألياف، مكسرات'],
                'is_active' => (bool) rand(0, 1),
                'image' => 'uploads/images/products/granola-bars.png',
            ],
        ];

        foreach ($products as $data) {
            $imagePath = $data['image'];
            unset($data['image']);

            $product = Product::create($data);

            $product->image()->create([
                'path' => $imagePath,
            ]);
        }
    }
}
